### ISSUE TITLE
AUTHENTICATE with Facebook

### ISSUE THREAD

**Issue by sherrysk8r** [sherryxue/informare#5]
We want to use Facebook authentication to keep track of users for the leaderboard and to do some analysis (i.e. mining their page likes and post likes for topics of interest to them).

**Comment by aayushtekriwal** [comment]
Found the steps on using facebook for login. Went through them, and it doesn't seem too difficult. Will work on adding it to the app as soon as I get back my computer -> most likely by EOD Wednesday.

Facebook Login for website / web app:

http://agelber.com/blog/adding-facebook-auth-to-rails/

https://developers.facebook.com/docs/facebook-login
https://developers.facebook.com/docs/facebook-login/web
